@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant  CampusManager
participant  System

activate CampusManager
CampusManager -> System : requests update of the passageway
activate System
CampusManager <- System : asks for information for the update of passageway
deactivate System
CampusManager -> System : sends information to the update of passageway
activate System
CampusManager <- System : delivers success or failure of the request update
deactivate System

@enduml
