@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant  CampusManager
participant  System

activate CampusManager
CampusManager -> System : requests creation of floor
activate System
CampusManager <- System : asks for information for the creation of floor
deactivate System
CampusManager -> System : sends information to the creation of floor
activate System
CampusManager <- System : delivers success or failure of the requests
deactivate System

@enduml
