@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor CampusManager
CampusManager -> SPA : selects option to get all floors for a certain building
activate SPA
CampusManager <- SPA : Displays the form to get the building request
deactivate SPA
CampusManager -> SPA : Indentifies beuilding
activate SPA
SPA -> MGC: "api/floors/buildingFinderId=param1" -> GET
activate MGC

MGC -> MGC: Handles the body request and get all Floors for building
activate MGC
deactivate MGC
SPA <- MGC: Response status and Json
CampusManager <- SPA: Shows the response status and Json





@enduml
