@startuml
'https://plantuml.com/sequence-diagram

autonumber

CampusManagerUI -> MDI : PATCH (/api/floorMaps)
 activate MDI
 MDI -> MDI: Handles the body request and saves FloorMap
 CampusManagerUI <- MDI: Response status and Json
participant  Planning


@enduml
