version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/python:3.10  # Update this to the correct version
      - image: circleci/mongo:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
          name: Install Dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Assuming your tests output results in a folder called 'test-results'
          #   - run:
          #       name: Run Tests
          #     command: npm test


    #  - store_test_results:
    #      path: tests

  #    - run:
  #        name: Start app with authentication
  #        command: |
  #          npm run start:auth &
  #          APP_PID=$!
  #          trap "kill $APP_PID" SIGINT
  #          wait $APP_PID

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
