@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor  CampusManager
participant  RoboDroneGo

activate CampusManager
CampusManager -> RoboDroneGo : requests building by elevator
activate RoboDroneGo
CampusManager <- RoboDroneGo : asks for building
deactivate RoboDroneGo
CampusManager -> RoboDroneGo : sends building to get elevators
activate RoboDroneGo
CampusManager <- RoboDroneGo : delivers success or failure of the request update
deactivate RoboDroneGo

@enduml
