@startuml
'https://plantuml.com/sequence-diagram

autonumber

FleetManagerUI -> MDI: "api/robots" -> Post
activate MDI
MDI -> MDI: Handles the body request,creates \n and saves the robot
FleetManagerUI <- MDI: Response status and Json
participant  Planning




@enduml
