@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor  CampusManager
participant  System

activate CampusManager
CampusManager -> System : requests creation of elevator
activate System
CampusManager <- System : asks for information for the creation of elevator
deactivate System
CampusManager -> System : sends information to the creation of elevator
activate System
CampusManager <- System : delivers success or failure of the requests
deactivate System

@enduml
