version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/python:3.10
      - image: circleci/mongo:latest

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install



workflows:
  version: 2
  build_and_test:
    jobs:
      - build
