@startuml
'https://plantuml.com/sequence-diagram

autonumber

CampusManagerUI -> MDI: "api/elevator" -> Put/Patch
activate MDI
MDI -> MDI: Handles the body request,updates \n and saves the elevator
CampusManagerUI <- MDI: Response status and Json
participant  Planning




@enduml
